### ISSUE TITLE
Option/filter to change/edit/remove loading .gif

### ISSUE THREAD

**Issue by greatknave** [enviragallery/soliloquy-lite#14]
https://secure.helpscout.net/conversation/1021200706/65692?folderId=3302566

Customer satisfied by the plugin overall — no complaints — but would like the option to change holder.gif path, as he uses CloudFront.

**Comment by dimensionmedia** [comment]
Issue moved to [enviragallery/soliloquy-plugin #633](https://github.com/enviragallery/soliloquy-plugin/issues/633) via [**ZenHub**](https://www.zenhub.com/)
