### ISSUE TITLE
Debug notice in admin

### ISSUE THREAD

**Issue by akyusa01** [enviragallery/soliloquy-lite#6]
I'm unable to repo this but there was no Can't Repo tag to mark this with.  I also did test with default WP theme and no other plugins and still see the debug notice in the admin.

`Notice : Undefined index: action in /home/kceemnes/domains/kceemnes.nl/public_html/wp-content/plugins/soliloquy-lite/includes/admin/editor.php on-line 84`

L84: `if ( $_GET['action'] == 'elementor' ) { `

I tried with Elementor activated on mtp and without.  Customer does not have Elementor installed or activated on their site.

Helpscout Ticket: https://secure.helpscout.net/conversation/612643844/33224/

## PHP info
<details>
<summary>System Info Data</summary>
PHP 7.2.3
MySQL 10.2.8-MariaDB

</details>

## Attached PHP Info
[PHP Info for KringloopCentrum EemnesHuizen.pdf](https://github.com/enviragallery/soliloquy-lite/files/2159603/PHP.Info.for.KringloopCentrum.EemnesHuizen.pdf)

## Expected Behavior
Shouldn't see a debug notice

## Current Behavior
Showing debug notice on Add Post/Add Page 

## Steps to Reproduce (for bugs)
I've been unable to repo this on mtp 

## Screenshots (if appropriate)
 
![screen shot 2018-07-03 at 9 37 39 am](https://user-images.githubusercontent.com/9019502/42223632-32f000e6-7ea6-11e8-9ca0-c23bbe6dade3.png)

**Comment by akyusa01** [comment]
Still unable to repo

**Comment by dimensionmedia** [comment]
line number doesn't even match up to anything anymore. closing.
